services:
  # PostgreSQL Database
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-pixshelf}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # PixShelf Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PORT=${PORT:-8080}
      - ENV=${ENV:-production}
      - DATABASE_URL=postgres://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@db:5432/${DB_NAME:-pixshelf}?sslmode=disable
      - IMAGE_STORAGE=/app/static/images
      - BASE_URL=${BASE_URL:-http://localhost:8080}
    volumes:
      - image_storage:/app/static/images
    ports:
      - "${PORT:-8080}:${PORT:-8080}"

volumes:
  postgres_data:
    driver: local
  image_storage:
    driver: local
