// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: images.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countImages = `-- name: CountImages :one
SELECT COUNT(*) FROM images
WHERE user_id = $1
`

func (q *Queries) CountImages(ctx context.Context, userID pgtype.Int4) (int64, error) {
	row := q.db.QueryRow(ctx, countImages, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSearchImages = `-- name: CountSearchImages :one
SELECT COUNT(*) FROM images
WHERE user_id = $1 AND (name ILIKE $2 OR description ILIKE $2)
`

type CountSearchImagesParams struct {
	UserID pgtype.Int4 `json:"user_id"`
	Name   string      `json:"name"`
}

func (q *Queries) CountSearchImages(ctx context.Context, arg CountSearchImagesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchImages, arg.UserID, arg.Name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createImage = `-- name: CreateImage :one
INSERT INTO images (
    name, description, file_path, mime_type, size_bytes, user_id
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, name, description, file_path, mime_type, size_bytes, created_at, updated_at, user_id
`

type CreateImageParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	FilePath    string      `json:"file_path"`
	MimeType    string      `json:"mime_type"`
	SizeBytes   int64       `json:"size_bytes"`
	UserID      pgtype.Int4 `json:"user_id"`
}

func (q *Queries) CreateImage(ctx context.Context, arg CreateImageParams) (Image, error) {
	row := q.db.QueryRow(ctx, createImage,
		arg.Name,
		arg.Description,
		arg.FilePath,
		arg.MimeType,
		arg.SizeBytes,
		arg.UserID,
	)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.FilePath,
		&i.MimeType,
		&i.SizeBytes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    google_id, email, name, avatar_url
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, google_id, email, name, avatar_url, created_at, updated_at
`

type CreateUserParams struct {
	GoogleID  string      `json:"google_id"`
	Email     string      `json:"email"`
	Name      string      `json:"name"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.GoogleID,
		arg.Email,
		arg.Name,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteImage = `-- name: DeleteImage :exec
DELETE FROM images
WHERE id = $1 AND user_id = $2
`

type DeleteImageParams struct {
	ID     int32       `json:"id"`
	UserID pgtype.Int4 `json:"user_id"`
}

func (q *Queries) DeleteImage(ctx context.Context, arg DeleteImageParams) error {
	_, err := q.db.Exec(ctx, deleteImage, arg.ID, arg.UserID)
	return err
}

const getImage = `-- name: GetImage :one
SELECT id, name, description, file_path, mime_type, size_bytes, created_at, updated_at, user_id FROM images
WHERE id = $1 LIMIT 1
`

// Images
func (q *Queries) GetImage(ctx context.Context, id int32) (Image, error) {
	row := q.db.QueryRow(ctx, getImage, id)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.FilePath,
		&i.MimeType,
		&i.SizeBytes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const getImageByUser = `-- name: GetImageByUser :one
SELECT id, name, description, file_path, mime_type, size_bytes, created_at, updated_at, user_id FROM images
WHERE id = $1 AND user_id = $2 LIMIT 1
`

type GetImageByUserParams struct {
	ID     int32       `json:"id"`
	UserID pgtype.Int4 `json:"user_id"`
}

func (q *Queries) GetImageByUser(ctx context.Context, arg GetImageByUserParams) (Image, error) {
	row := q.db.QueryRow(ctx, getImageByUser, arg.ID, arg.UserID)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.FilePath,
		&i.MimeType,
		&i.SizeBytes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, google_id, email, name, avatar_url, created_at, updated_at FROM users
WHERE id = $1 LIMIT 1
`

// Users
func (q *Queries) GetUser(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, google_id, email, name, avatar_url, created_at, updated_at FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByGoogleID = `-- name: GetUserByGoogleID :one
SELECT id, google_id, email, name, avatar_url, created_at, updated_at FROM users
WHERE google_id = $1 LIMIT 1
`

func (q *Queries) GetUserByGoogleID(ctx context.Context, googleID string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByGoogleID, googleID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listImages = `-- name: ListImages :many
SELECT id, name, description, file_path, mime_type, size_bytes, created_at, updated_at, user_id FROM images
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListImagesParams struct {
	UserID pgtype.Int4 `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListImages(ctx context.Context, arg ListImagesParams) ([]Image, error) {
	rows, err := q.db.Query(ctx, listImages, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Image
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.FilePath,
			&i.MimeType,
			&i.SizeBytes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImagesCursor = `-- name: ListImagesCursor :many
SELECT id, name, description, file_path, mime_type, size_bytes, created_at, updated_at, user_id FROM images
WHERE user_id = $1 AND id < $2
ORDER BY id DESC
LIMIT $3
`

type ListImagesCursorParams struct {
	UserID pgtype.Int4 `json:"user_id"`
	ID     int32       `json:"id"`
	Limit  int32       `json:"limit"`
}

func (q *Queries) ListImagesCursor(ctx context.Context, arg ListImagesCursorParams) ([]Image, error) {
	rows, err := q.db.Query(ctx, listImagesCursor, arg.UserID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Image
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.FilePath,
			&i.MimeType,
			&i.SizeBytes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchImages = `-- name: SearchImages :many
SELECT id, name, description, file_path, mime_type, size_bytes, created_at, updated_at, user_id FROM images
WHERE user_id = $1 AND (name ILIKE $2 OR description ILIKE $2)
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type SearchImagesParams struct {
	UserID pgtype.Int4 `json:"user_id"`
	Name   string      `json:"name"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) SearchImages(ctx context.Context, arg SearchImagesParams) ([]Image, error) {
	rows, err := q.db.Query(ctx, searchImages,
		arg.UserID,
		arg.Name,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Image
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.FilePath,
			&i.MimeType,
			&i.SizeBytes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchImagesCursor = `-- name: SearchImagesCursor :many
SELECT id, name, description, file_path, mime_type, size_bytes, created_at, updated_at, user_id FROM images
WHERE user_id = $1 AND id < $2 AND (name ILIKE $3 OR description ILIKE $3)
ORDER BY id DESC
LIMIT $4
`

type SearchImagesCursorParams struct {
	UserID pgtype.Int4 `json:"user_id"`
	ID     int32       `json:"id"`
	Name   string      `json:"name"`
	Limit  int32       `json:"limit"`
}

func (q *Queries) SearchImagesCursor(ctx context.Context, arg SearchImagesCursorParams) ([]Image, error) {
	rows, err := q.db.Query(ctx, searchImagesCursor,
		arg.UserID,
		arg.ID,
		arg.Name,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Image
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.FilePath,
			&i.MimeType,
			&i.SizeBytes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateImage = `-- name: UpdateImage :one
UPDATE images
SET name = $2,
    description = $3,
    updated_at = NOW()
WHERE id = $1 AND user_id = $4
RETURNING id, name, description, file_path, mime_type, size_bytes, created_at, updated_at, user_id
`

type UpdateImageParams struct {
	ID          int32       `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	UserID      pgtype.Int4 `json:"user_id"`
}

func (q *Queries) UpdateImage(ctx context.Context, arg UpdateImageParams) (Image, error) {
	row := q.db.QueryRow(ctx, updateImage,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.UserID,
	)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.FilePath,
		&i.MimeType,
		&i.SizeBytes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET name = $2,
    avatar_url = $3,
    updated_at = NOW()
WHERE id = $1
RETURNING id, google_id, email, name, avatar_url, created_at, updated_at
`

type UpdateUserParams struct {
	ID        int32       `json:"id"`
	Name      string      `json:"name"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.ID, arg.Name, arg.AvatarUrl)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
