// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Image struct {
	ID          int32              `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	FilePath    string             `json:"file_path"`
	MimeType    string             `json:"mime_type"`
	SizeBytes   int64              `json:"size_bytes"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
