// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountImages(ctx context.Context, userID pgtype.Int4) (int64, error)
	CountSearchImages(ctx context.Context, arg CountSearchImagesParams) (int64, error)
	CreateImage(ctx context.Context, arg CreateImageParams) (Image, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteImage(ctx context.Context, arg DeleteImageParams) error
	// Images
	GetImage(ctx context.Context, id int32) (Image, error)
	GetImageByUser(ctx context.Context, arg GetImageByUserParams) (Image, error)
	// Users
	GetUser(ctx context.Context, id int32) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByGoogleID(ctx context.Context, googleID string) (User, error)
	ListImages(ctx context.Context, arg ListImagesParams) ([]Image, error)
	SearchImages(ctx context.Context, arg SearchImagesParams) ([]Image, error)
	UpdateImage(ctx context.Context, arg UpdateImageParams) (Image, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
