// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"context"
)

type Querier interface {
	CountImages(ctx context.Context) (int64, error)
	CountSearchImages(ctx context.Context, name string) (int64, error)
	CreateImage(ctx context.Context, arg CreateImageParams) (Image, error)
	DeleteImage(ctx context.Context, id int32) error
	GetImage(ctx context.Context, id int32) (Image, error)
	ListImages(ctx context.Context, arg ListImagesParams) ([]Image, error)
	SearchImages(ctx context.Context, arg SearchImagesParams) ([]Image, error)
	UpdateImage(ctx context.Context, arg UpdateImageParams) (Image, error)
}

var _ Querier = (*Queries)(nil)
